# -*- coding: utf-8 -*-
"""教育大數據.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QDtffeJ_brOf2UdHiuXJU7CxZo_R80i4

1-1
"""

import pandas as pd
df = pd.read_csv('/content/edu_bigdata_imp1.csv',encoding = 'big5',low_memory = False)
df_filtered =  df [df['PseudoID'] == 39]
unique_values = df_filtered['dp001_review_sn'].unique()
print(len(unique_values))

"""1-2"""

import pandas as pd
df = pd.read_csv('/content/edu_bigdata_imp1.csv',encoding = 'big5',low_memory = False)
df_filtered = df[df['PseudoID']==39]
df_filtered = df_filtered.dropna(subset = ['dp001_question_sn'])
unique_values = df_filtered['dp001_question_sn'].unique()
print(len(unique_values))

"""2-1"""

import pandas as pd
df = pd.read_csv('/content/edu_bigdata_imp1.csv',encoding = 'big5',low_memory = False)
df_filtered =  df [df['PseudoID'] == 281]
df_filtered = df_filtered.dropna(subset=['dp001_indicator'])
unique = df_filtered.drop_duplicates(subset = 'dp001_video_item_sn')
print(unique[['dp001_video_item_sn','dp001_indicator']])

"""2-2"""

import pandas as pd
df = pd.read_csv('/content/edu_bigdata_imp1.csv',encoding = 'big5',low_memory = False)
df_filtered = df[(df['dp001_prac_score_rate'] == 100) & (df['PseudoID']==281) ]
ans = len(df_filtered)
print(ans)

"""3-1"""

import pandas as pd
df = pd.read_csv('/content/edu_bigdata_imp1.csv',encoding = 'big5',low_memory = False)
df_filtered = df[(df['dp001_record_plus_view_action'] == 'paused') & (df['PseudoID'] == 71)]
ans = len(df_filtered)
print(ans)

"""3-2"""

import pandas as pd
df = pd.read_csv('/content/edu_bigdata_imp1.csv',encoding = 'big5',low_memory = False)
df_filtered =  df [df['PseudoID'] == 71]
d = df_filtered['dp001_review_start_time']
s = pd.Series(pd.to_datetime(d))
ans = s.dt.date
ans = ans.unique()
print(ans)

"""4-1"""

import pandas as pd
df = pd.read_csv('/content/edu_bigdata_imp1.csv',encoding = 'big5',low_memory = False)
col = df['dp001_review_sn']
num = col.value_counts()
ans = num.idxmax()

print(int(ans))

"""4-2"""

import pandas as pd
df = pd.read_csv('/content/edu_bigdata_imp1.csv',encoding = 'big5',low_memory = False)
title = df[df['dp002_extensions_alignment'] == '["十二年國民基本教育類"]']
ans = len(title)

print(ans)

"""4-3"""

import pandas as pd
df = pd.read_csv('/content/edu_bigdata_imp1.csv',encoding = 'big5',low_memory = False)
table = df['dp002_verb_display_zh_TW']
cnt = table.value_counts()
ans = cnt.head(3)
print(ans)

"""4-4"""

import pandas as pd
df = pd.read_csv('/content/edu_bigdata_imp1.csv',encoding = 'big5',low_memory = False)
title = df[df['dp002_extensions_alignment'] == '["校園職業安全"]']
ans = len(title)

print(ans)